define(['./collection/at', './collection/countBy', './collection/each', './collection/eachRight', './collection/every', './collection/filter', './collection/find', './collection/findLast', './collection/forEach', './collection/forEachRight', './collection/groupBy', './collection/includes', './collection/invokeMap', './collection/keyBy', './collection/map', './collection/partition', './collection/reduce', './collection/reduceRight', './collection/reject', './collection/sample', './collection/sampleSize', './collection/shuffle', './collection/size', './collection/some', './collection/sortBy', './collection/sortByOrder'], function(at, countBy, each, eachRight, every, filter, find, findLast, forEach, forEachRight, groupBy, includes, invokeMap, keyBy, map, partition, reduce, reduceRight, reject, sample, sampleSize, shuffle, size, some, sortBy, sortByOrder) {
  return {
    'at': at,
    'countBy': countBy,
    'each': each,
    'eachRight': eachRight,
    'every': every,
    'filter': filter,
    'find': find,
    'findLast': findLast,
    'forEach': forEach,
    'forEachRight': forEachRight,
    'groupBy': groupBy,
    'includes': includes,
    'invokeMap': invokeMap,
    'keyBy': keyBy,
    'map': map,
    'partition': partition,
    'reduce': reduce,
    'reduceRight': reduceRight,
    'reject': reject,
    'sample': sample,
    'sampleSize': sampleSize,
    'shuffle': shuffle,
    'size': size,
    'some': some,
    'sortBy': sortBy,
    'sortByOrder': sortByOrder
  };
});
